# ☀️ Suryabandhu

### Smart IoT-Based Load Monitoring and Dynamic Solar Energy Allocation System for Multi-Flat Residential Buildings

Suryabandhu is a prototype system designed to demonstrate **shared rooftop solar energy monitoring, household load monitoring, solar energy allocation, fair-split billing, savings estimation, and fault detection** for multi-flat residential buildings.

The project combines a **web-based monitoring dashboard** with an **Arduino-based hardware prototype** to represent how a shared solar-energy system can be monitored and managed at the household level.

Simulation LINK__-- https://www.tinkercad.com/things/fckQXyhZyI5-iot-based-load-monitoring-amp-solar-energy-allocation-system?sharecode=jD-KeIXDOLeE7DkDjxXSzLGUAMWJ72Q0PpV8WV6USQQ
---

## 📌 Table of Contents

- [Overview](#-overview)
- [Problem Statement](#-problem-statement)
- [Objectives](#-objectives)
- [Key Features](#-key-features)
- [System Architecture](#-system-architecture)
- [Hardware Prototype](#-hardware-prototype)
- [Hardware Components](#-hardware-components)
- [Software](#-software)
- [Dashboard](#-dashboard)
- [How the Prototype Works](#-how-the-prototype-works)
- [Project Structure](#-project-structure)
- [Running the Dashboard](#-running-the-dashboard)
- [Tinkercad Simulation](#-tinkercad-simulation)
- [Circuit Design](#-circuit-design)
- [Current Prototype Limitations](#-current-prototype-limitations)
- [Future Improvements](#-future-improvements)
- [Applications](#-applications)
- [Project Status](#-project-status)
- [License](#-license)

---

# 🔎 Overview

Residential buildings with shared rooftop solar systems need a way to monitor:

- Solar energy generation
- Household electricity consumption
- Grid electricity usage
- Solar energy allocation
- Household savings
- Individual household load status
- Possible faults or abnormal power usage

**Suryabandhu** presents a prototype solution for these requirements.

The system consists of two main parts:

1. **Hardware Prototype** — an Arduino-based circuit representing household loads, solar availability, status indicators, and an LCD interface.
2. **Web Dashboard** — a browser-based interface that displays solar generation, grid usage, household loads, savings, billing information, and fault alerts.

---

# 🎯 Problem Statement

In a multi-flat residential building with a shared rooftop solar installation, electricity generated by the solar system needs to be monitored and allocated efficiently.

A conventional electricity system may not provide residents with a clear view of:

- How much solar energy is being generated
- How much electricity individual flats are consuming
- How much energy is being obtained from the grid
- How much each household is saving
- Whether a household or meter node is behaving abnormally

Suryabandhu explores a digital monitoring approach that combines household-level load representation with a centralized dashboard.

---

# 🎯 Objectives

The main objectives of Suryabandhu are:

- Monitor household electrical loads.
- Represent shared solar energy availability.
- Display household-level energy information.
- Track solar and grid energy usage.
- Estimate household savings.
- Demonstrate fair-split billing based on usage.
- Detect abnormal drops in household output.
- Display system status through LEDs and an LCD.
- Provide a centralized web dashboard for monitoring.
- Demonstrate a possible IoT architecture for residential solar management.

---

# ✨ Key Features

## ☀️ Solar Energy Monitoring

The dashboard displays solar generation information and provides a centralized view of the shared rooftop solar system.

## ⚡ Household Load Monitoring

Individual household loads are represented and monitored through the prototype.

The dashboard displays household power information such as:

- Current power usage
- Solar energy used
- Grid energy used
- Household status

## 🔋 Solar Energy Allocation

The project demonstrates the concept of allocating available solar energy among multiple household loads.

## 💰 Fair-Split Billing

The dashboard includes a billing section that estimates household costs according to energy usage rather than simply dividing the total bill equally.

The prototype uses an assumed grid-equivalent rate for the calculation.

## 📊 Savings Estimation

The dashboard estimates savings resulting from the use of solar energy.

## 🚨 Fault Detection

The dashboard prototype can simulate abnormal household output and flag a possible fault.

A household can transition from:

`Normal`

to:

`Fault flagged`

The prototype then demonstrates the process of detecting and resolving the simulated issue.

## 💡 LED Status Indicators

The hardware prototype contains multiple LEDs that can represent the status of different loads or system conditions.

## 🖥️ LCD Display

The hardware design includes an I²C 16×2 LCD for displaying information locally.

---

# 🏗️ System Architecture

The intended architecture of the project can be represented as:

```text
                    ☀️ SHARED SOLAR ROOFTOP
                             │
                             ▼
                    Solar Energy Input
                             │
                             ▼
                    ┌─────────────────┐
                    │ Arduino / IoT   │
                    │ Controller      │
                    └─────────────────┘
                             │
              ┌──────────────┼──────────────┐
              │              │              │
              ▼              ▼              ▼
        Household       Solar Input     Status LEDs
          Loads
              │              │
              └──────────────┼──────────────┘
                             ▼
                       LCD Display
                             │
                             ▼
                    Monitoring System
                             │
                             ▼
                    Web Dashboard
                             │
            ┌────────────────┼────────────────┐
            ▼                ▼                ▼
       Load Usage       Solar Usage       Grid Usage
            │                │                │
            └────────────────┼────────────────┘
                             ▼
                    Billing & Savings
                             │
                             ▼
                     Fault Monitoring
